<?php

return [
    'app_name' => 'Mechinno Management Panel',
    'timezone' => 'Asia/Tehran',
    'debug' => false,

    /*
     * IMPORTANT:
     * Change this password before uploading to production.
     * You can later replace "password" with "password_hash" generated by:
     * php -r "echo password_hash('YOUR_STRONG_PASSWORD', PASSWORD_DEFAULT), PHP_EOL;"
     */
    'auth' => [
        'enabled' => true,
        'username' => 'admin',
        'password' => 'CHANGE_ME',
        'password_hash' => '',
        'viewer_username' => 'viewer',
        'viewer_password' => 'CHANGE_ME_VIEWER',
        'viewer_password_hash' => '',
    ],

    /*
     * cPanel path:
     * 1. Create a MySQL database and user in cPanel.
     * 2. Copy this file to config.php.
     * 3. Put your database name, username, and password below.
     */
    'db' => [
        'driver' => 'mysql',
        'host' => 'localhost',
        'port' => 3306,
        'database' => 'cpaneluser_mechinno',
        'username' => 'cpaneluser_mechinno',
        'password' => 'CHANGE_ME',
        'charset' => 'utf8mb4',
    ],

    /*
     * Optional local development fallback:
     *
     * 'db' => [
     *     'driver' => 'sqlite',
     *     'path' => __DIR__ . '/data/mechinno.sqlite3',
     * ],
     */
];
